const fs = require('fs');
const path = require('path');

// Month days specification for leap year (366 days)
const MONTHS = [
  { month: 1, namePt: "Janeiro", nameEn: "January", days: 31, themeId: "hardware-software", themeNumber: 1, themeTitlePt: "Hardware e Software", themeTitleEn: "Hardware and Software", badgeColor: "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300", categoryPt: "Fundamentos de TIC", categoryEn: "ICT Fundamentals" },
  { month: 2, namePt: "Fevereiro", nameEn: "February", days: 29, themeId: "ergonomia", themeNumber: 2, themeTitlePt: "Ergonomia e Saúde Digital", themeTitleEn: "Ergonomics & Digital Health", badgeColor: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300", categoryPt: "Ergonomia e Postura", categoryEn: "Ergonomics & Posture" },
  { month: 3, namePt: "Março", nameEn: "March", days: 31, themeId: "palavras-passe", themeNumber: 3, themeTitlePt: "Palavras-passe e Autenticação", themeTitleEn: "Passwords & Authentication", badgeColor: "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300", categoryPt: "Segurança de Acessos", categoryEn: "Access Security" },
  { month: 4, namePt: "Abril", nameEn: "April", days: 30, themeId: "seguranca", themeNumber: 4, themeTitlePt: "Segurança e Privacidade Online", themeTitleEn: "Online Safety & Privacy", badgeColor: "bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300", categoryPt: "Proteção Digital", categoryEn: "Digital Protection" },
  { month: 5, namePt: "Maio", nameEn: "May", days: 31, themeId: "correio-eletronico", themeNumber: 5, themeTitlePt: "Correio Eletrónico e Comunicação", themeTitleEn: "Email & Communication", badgeColor: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/40 dark:text-indigo-300", categoryPt: "Comunicação Digital", categoryEn: "Digital Communication" },
  { month: 6, namePt: "Junho", nameEn: "June", days: 30, themeId: "navegar-internet", themeNumber: 6, themeTitlePt: "Navegar na Internet e Pesquisa", themeTitleEn: "Web Browsing & Research", badgeColor: "bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300", categoryPt: "Pesquisa na Web", categoryEn: "Web Search" },
  { month: 7, namePt: "Julho", nameEn: "July", days: 31, themeId: "direitos-autor", themeNumber: 7, themeTitlePt: "Direitos de Autor e Licenciamento", themeTitleEn: "Copyright & Licensing", badgeColor: "bg-rose-100 text-rose-800 dark:bg-rose-900/40 dark:text-rose-300", categoryPt: "Ética e Licenciamento", categoryEn: "Ethics & Licensing" },
  { month: 8, namePt: "Agosto", nameEn: "August", days: 31, themeId: "ficheiros-nuvem", themeNumber: 8, themeTitlePt: "Ficheiros, Organização e Nuvem", themeTitleEn: "Files, Organization & Cloud", badgeColor: "bg-cyan-100 text-cyan-800 dark:bg-cyan-900/40 dark:text-cyan-300", categoryPt: "Gestão de Ficheiros", categoryEn: "File Management" },
  { month: 9, namePt: "Setembro", nameEn: "September", days: 30, themeId: "cidadania-digital", themeNumber: 9, themeTitlePt: "Cidadania Digital e Netiqueta", themeTitleEn: "Digital Citizenship & Netiquette", badgeColor: "bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-300", categoryPt: "Cidadania Digital", categoryEn: "Digital Citizenship" },
  { month: 10, namePt: "Outubro", nameEn: "October", days: 31, themeId: "redes-internet", themeNumber: 10, themeTitlePt: "Redes e Funcionamento da Internet", themeTitleEn: "Networks & Internet Mechanics", badgeColor: "bg-violet-100 text-violet-800 dark:bg-violet-900/40 dark:text-violet-300", categoryPt: "Redes e Ligação", categoryEn: "Networks & Connectivity" },
  { month: 11, namePt: "Novembro", nameEn: "November", days: 30, themeId: "programacao-logica", themeNumber: 11, themeTitlePt: "Algoritmos e Pensamento Computacional", themeTitleEn: "Algorithms & Computational Thinking", badgeColor: "bg-orange-100 text-orange-800 dark:bg-orange-900/40 dark:text-orange-300", categoryPt: "Lógica e Algoritmos", categoryEn: "Logic & Algorithms" },
  { month: 12, namePt: "Dezembro", nameEn: "December", days: 31, themeId: "ia-futuro", themeNumber: 12, themeTitlePt: "Inteligência Artificial e Tecnologias", themeTitleEn: "Artificial Intelligence & Tech", badgeColor: "bg-fuchsia-100 text-fuchsia-800 dark:bg-fuchsia-900/40 dark:text-fuchsia-300", categoryPt: "Tecnologia e Futuro", categoryEn: "Technology & Future" }
];

console.log("Generator script initialized.");
