import json

def get_366_tips():
    tips = []
    day_count = 0
    
    # Month meta definition
    months_meta = [
        ("Janeiro", "January", 31, 1, "hardware-software", 1, "Hardware e Software", "Hardware and Software", "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300", "Fundamentos de TIC", "ICT Fundamentals", "Monitor"),
        ("Fevereiro", "February", 29, 2, "ergonomia", 2, "Ergonomia e Saúde Digital", "Ergonomics & Digital Health", "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300", "Ergonomia e Postura", "Ergonomics & Posture", "Heart"),
        ("Março", "March", 31, 3, "palavras-passe", 3, "Palavras-passe e Autenticação", "Passwords & Authentication", "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300", "Segurança de Acessos", "Access Security", "KeyRound"),
        ("Abril", "April", 30, 4, "seguranca", 4, "Segurança e Privacidade Online", "Online Safety & Privacy", "bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300", "Proteção Digital", "Digital Protection", "ShieldCheck"),
        ("Maio", "May", 31, 5, "correio-eletronico", 5, "Correio Eletrónico e Comunicação", "Email & Communication", "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/40 dark:text-indigo-300", "Comunicação Digital", "Digital Communication", "Mail"),
        ("Junho", "June", 30, 6, "navegar-internet", 6, "Navegar na Internet e Pesquisa", "Web Browsing & Research", "bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300", "Pesquisa na Web", "Web Search", "Globe"),
        ("Julho", "July", 31, 7, "direitos-autor", 7, "Direitos de Autor e Licenciamento", "Copyright & Licensing", "bg-rose-100 text-rose-800 dark:bg-rose-900/40 dark:text-rose-300", "Ética e Licenciamento", "Ethics & Licensing", "Copyright"),
        ("Agosto", "August", 31, 8, "ficheiros-nuvem", 8, "Ficheiros, Organização e Nuvem", "Files, Organization & Cloud", "bg-cyan-100 text-cyan-800 dark:bg-cyan-900/40 dark:text-cyan-300", "Gestão de Ficheiros", "File Management", "Folder"),
        ("Setembro", "September", 30, 9, "cidadania-digital", 9, "Cidadania Digital e Netiqueta", "Digital Citizenship & Netiquette", "bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-300", "Cidadania Digital", "Digital Citizenship", "Users"),
        ("Outubro", "October", 31, 10, "redes-internet", 10, "Redes e Funcionamento da Internet", "Networks & Internet Mechanics", "bg-violet-100 text-violet-800 dark:bg-violet-900/40 dark:text-violet-300", "Redes e Ligação", "Networks & Connectivity", "Wifi"),
        ("Novembro", "November", 30, 11, "programacao-logica", 11, "Algoritmos e Pensamento Computacional", "Algorithms & Computational Thinking", "bg-orange-100 text-orange-800 dark:bg-orange-900/40 dark:text-orange-300", "Lógica e Algoritmos", "Logic & Algorithms", "Cpu"),
        ("Dezembro", "December", 31, 12, "ia-futuro", 12, "Inteligência Artificial e Tecnologias", "Artificial Intelligence & Tech", "bg-fuchsia-100 text-fuchsia-800 dark:bg-fuchsia-900/40 dark:text-fuchsia-300", "Tecnologia e Futuro", "Technology & Future", "Sparkles")
    ]

    # Subtopics per month (31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
    # Total = 366 topics
    
    # Month 1: Hardware & Software
    m1_topics = [
        ("O Computador e as Suas Partes", "Entender como o computador combina componentes físicos e programas.", "O computador é um sistema formado por partes físicas (hardware) e instruções virtuais (software) que trabalham juntas.", "Sem hardware o computador não existe, e sem software o computador não sabe o que fazer!", "A palavra 'computer' significava originalmente uma pessoa que fazia cálculos matemáticos à mão!"),
        ("CPU: O Cérebro do Computador", "A Unidade Central de Processamento que executa todas as instruções.", "O processador (CPU) interpreta e executa as ordens de todos os programas instalados.", "Sem o processador, nenhum programa consegue funcionar no computador.", "A velocidade do processador pode ser indicada em GHz, e o seu rendimento depende de vários fatores."),
        ("Memória RAM: A Secretária de Trabalho", "A memória temporária de acesso rápido do computador.", "A memória RAM guarda as informações que estás a utilizar exatamente no momento em que trabalhas.", "Quando o computador é desligado, o conteúdo da memória RAM é totalmente apagado.", "Quanto mais memória RAM tiveres, mais programas podes ter abertos ao mesmo tempo sem o computador diminuir o ritmo."),
        ("Disco SSD: Armazenamento Permanente", "O local onde guardas os teus ficheiros e trabalhos para o futuro.", "O disco SSD guarda o sistema operativo, os programas e os teus documentos mesmo quando o computador é desligado.", "Um SSD guarda os teus ficheiros mesmo quando desligas o computador, mas é importante fazer cópias de segurança.", "Ao contrário dos antigos discos rígidos com agulhas magnéticas, os discos SSD usam chips eletrónicos sem peças móveis."),
        ("Periféricos de Entrada", "Dispositivos que enviam informação do mundo exterior para o computador.", "Teclado, rato, microfone, câmara web e scanner são exemplos de componentes que introduzem dados no sistema.", "Permitem que dês ordens e comuniques diretamente com o teu computador.", "O primeiro rato de computador foi inventado nos anos 60 e era feito de madeira com duas rodas de metal!"),
        ("Periféricos de Saída", "Dispositivos que mostram ou reproduzem o resultado do trabalho.", "Monitor, colunas de som, auscultadores e impressoras transmitem informação do computador para ti.", "Permitem-te ver, ouvir ou imprimir o trabalho que realizaste.", "Os primeiros monitores só conseguiam mostrar texto verde ou laranja num fundo completamente preto."),
        ("Periféricos Mistos", "Dispositivos que conseguem enviar e receber informação ao mesmo tempo.", "Ecrãs táteis e pen drives são exemplos de dispositivos com dupla função de entrada e saída.", "Facilitam a interatividade e a transferência rápida de dados num único equipamento.", "Um ecrã tátil deteta as pequenas cargas elétricas da ponta dos teus dedos para saber onde estás a tocar."),
        ("O Sistema Operativo", "O programa principal que gere todos os recursos do computador.", "Exemplos como Windows, Linux e macOS organizam a memória, os ficheiros e o ecrã para potenciar a utilização.", "É o primeiro programa a carregar e permite que todos os outros funcionem em harmonia.", "Sem o sistema operativo, terias de escrever comandos em código binário para fazer qualquer tarefa básica!"),
        ("Bits e Bytes: A Linguagem Binária", "Como o computador representa todos os dados usando apenas 0 e 1.", "Um bit é a menor unidade de informação (0 ou 1) e 8 bits formam exatamente 1 byte.", "Tudo o que vês no ecrã (texto, imagem, som) é traduzido em sequências binárias de zeros e uns.", "A letra 'A' maiúscula é representada no computador pela sequência binária 01000001!"),
        ("Placa Gráfica (GPU)", "O componente especializado em desenhar imagens e vídeos no ecrã.", "A GPU processa milhares de dados visuais em simultâneo para jogos e aplicações multimédia.", "Garante que os vídeos e animações funcionem de forma fluida e sem interrupções.", "Placas gráficas modernas conseguem calcular biliões de pontos de luz por segundo em tempo real."),
        ("Placa de Rede e Wi-Fi", "O componente que permite ao computador comunicar com outros dispositivos.", "Permite ligar o teu equipamento à Internet por cabo de rede ou por ondas de rádio (Wi-Fi).", "Sem placa de rede, o teu computador fica totalmente isolado do resto do mundo digital.", "A tecnologia Wi-Fi utiliza ondas de rádio semelhantes às das emissoras de rádio comerciais."),
        ("A Placa-Mãe (Motherboard)", "A grande placa de circuitos que liga todos os componentes do computador.", "Conecta a CPU, a RAM, o disco, a placa de rede e todos os periféricos numa única estrutura.", "Garante que a eletricidade e os dados fluam corretamente entre todas as partes.", "A motherboard tem milhares de caminhos de cobre microscópicos desenhados na sua superfície."),
        ("Software de Sistema vs Software de Aplicação", "Compreender a diferença entre programas de gestão e ferramentas do utilizador.", "O software de sistema controla o hardware, enquanto o software de aplicação ajuda-te em tarefas específicas como desenhar ou escrever.", "Ajuda-te a saber que tipo de programa precisas para cada objetivo escolar.", "Existem milhões de aplicações no mundo, mas todas dependem de um software de sistema estável."),
        ("Atualizações de Software", "Melhorar programas e corrigir falhas de segurança no sistema.", "As atualizações instalam correções, fecham vulnerabilidades e adicionam novas funcionalidades úteis.", "Manter os programas atualizados ajuda a proteger o teu computador contra ameaças.", "Muitas atualizações corrigem falhas que foram descobertas recentemente por especialistas em segurança."),
        ("Atalhos de Teclado Essenciais (Ctrl+C e Ctrl+V)", "Aumentar a rapidez de trabalho ao copiar e colar elementos.","Pressionar Ctrl+C copia um elemento selecionado e Ctrl+V cola-o no local desejado.", "Economiza imenso tempo ao organizar apontamentos e trabalhos de TIC.", "O atalho Ctrl+Z permite desfazer o último erro cometido num programa!"),
        ("O Rato e o Botão Direito", "Descobrir os menus de contexto ocultos no ecrã.", "Clicar com o botão direito do rato abre um menu especial com opções de atalho para o elemento selecionado.", "Dá-te acesso rápido a comandos como renomear, apagar ou ver propriedades.", "O duplo clique do botão esquerdo serve para abrir ficheiros e aplicações."),
        ("O Touchpad nos Portáteis", "Usar gestos com os dedos para navegar sem precisar de rato externo.", "Permite mover o cursor, fazer scroll com dois dedos e aproximar com o gesto de pinça.", "É uma ferramenta prática para quando estás a estudar fora de casa.", "Os touchpads modernos conseguem detetar até quatro dedos ao mesmo tempo!"),
        ("Ficheiros Executáveis (.exe)", "Os programas que iniciam instalações ou aplicações no computador.", "Ficheiros com a extensão .exe contêm instruções diretas para o processador executar.", "Exigem cuidados especiais antes de serem abertos para garantir que vêm de fontes seguras.", "Nunca deves abrir um ficheiro .exe desconhecido recebido por email sem autorização de um adulto."),
        ("Formatos de Ficheiro Populares", "Reconhecer documentos, imagens, sons e vídeos pelas suas extensões.", "Documentos (.docx, .pdf), imagens (.png, .jpg) e áudio (.mp3) têm características próprias.", "Ajuda-te a escolher o programa certo para abrir cada ficheiro.", "A extensão indica ao sistema operativo qual a aplicação adequada para abrir o documento."),
        ("Resolução do Monitor e Pixéis", "Como os pequenos pontos de cor formam as imagens no ecrã.", "Um pixel é o menor ponto colorido do ecrã, e a resolução mede a quantidade total de pixéis na imagem.", "Resoluções mais altas oferecem imagens mais nítidas e detalhadas.", "Um ecrã Full HD tem mais de 2 milhões de pixéis a mudar de cor dezenas de vezes por segundo!"),
        ("A Alimentação do Computador e Bateria", "Cuidados ao carregar e conservar a energia dos equipamentos.", "Os computadores usam transformadores para converter a corrente da tomada na voltagem correta.", "Usar carregadores originais protege a bateria e evita sobreaquecimentos.", "Evitar deixar a bateria descarregar completamente até 0% ajuda a prolongar a sua vida útil."),
        ("Limpeza Física Segura dos Equipamentos", "Manter o ecrã, o teclado e as entradas livres de poeira.", "Usar panos de microfibra ligeiramente humedecidos e ar comprimido sem aplicar produtos químicos agressivos.", "Evita que os componentes aqueçam e prolonga a vida do teu computador.", "Nunca deves borrifar líquidos diretamente sobre o ecrã ou o teclado do equipamento!"),
        ("O Que Fazer Quando um Programa Encrava", "Resolver bloqueios temporários de forma calma e controlada.", "Usar o Gestor de Tarefas para fechar a aplicação bloqueada sem desligar o computador à força.", "Evita perder trabalhos que tenhas abertos noutras aplicações.", "Desligar o computador no botão de energia deve ser apenas o último recurso em caso de bloqueio total."),
        ("Dispositivos de Armazenamento Externo", "Usar pen drives e discos externos para transportar trabalhos.", "Permitem guardar cópias dos teus projetos escolares e levá-los para a aula de TIC.", "Facilitam a partilha segura de ficheiros entre computadores sem necessidade de Internet.", "Deves sempre ejetar com segurança a pen drive no sistema operativo antes de a retirar da porta USB."),
        ("A Evolução dos Computadores", "Como os computadores passaram de salas inteiras a pequenos tablets.", "Os primeiros computadores ocupavam divisões gigantescas e hoje temos equipamentos potentes no bolso.", "Mostra como a tecnologia evolui rapidamente para ser mais eficiente e acessível.", "O ENIAC, um dos primeiros computadores, pesava 30 toneladas e usava 18 mil válvulas de vidro!"),
        ("Microprocessadores em Objetos do Dia a Dia", "Descobrir a computação em carros, frigoríficos e brinquedos.", "Muitos eletrodomésticos modernos contêm pequenos computadores chamados microcontroladores.", "Demonstra que a informática está presente em quase tudo ao nosso redor.", "Um carro moderno pode ter mais de 100 pequenos microprocessadores a controlar a condução e a segurança!"),
        ("A Inicialização do Sistema (BIOS/UEFI)", "O primeiro programa que acorda o hardware do computador.", "A BIOS verifica se a memória RAM, o teclado e o disco estão a funcionar antes de carregar o sistema.", "Garante que o equipamento está pronto e seguro antes de começares a trabalhar.", "É um programa guardado num chip especial da motherboard que nunca se apaga mesmo sem bateria."),
        ("A Importância de Reiniciar o Computador", "Como o reiniciar limpa a memória RAM e resolve pequenas falhas.", "Reiniciar fecha todos os processos em segundo plano e recarrega o sistema operativo limpo.", "É a solução simples e rápida para corrigir lentidões ou erros temporários.", "Muitas atualizações só ficam completamente concluídas após o reiniciar do sistema."),
        ("O Gestor de Tarefas", "Uma ferramenta do sistema para ver o consumo de recursos.", "Mostra quanto da CPU, RAM e disco está a ser utilizado por cada programa em tempo real.", "Ajuda-te a identificar que aplicação está a tornar o computador mais lento.", "Podes abrir o Gestor de Tarefas pressionando as teclas Ctrl + Shift + Esc no Windows!"),
        ("Compressão de Ficheiros (.zip)", "Juntar e diminuir o tamanho de vários ficheiros numa única pasta.", "A compressão reorganiza os dados para ocuparem menos espaço no disco ou no envio de trabalhos.", "Facilita o envio de múltiplos documentos de uma só vez para o professor.", "Ao comprimir um ficheiro de texto, o programa substitui palavras repetidas por códigos mais curtos!"),
        ("Reciclagem Segura de Equipamentos Eletrónicos", "O destino correto para computadores e telemóveis antigos (REEE).", "Equipamentos eletrónicos velhos contêm materiais valiosos e não devem ser deitados no lixo comum.", "Protege o ambiente e permite reaproveitar metais preciosos de forma sustentável.", "Podes entregar equipamentos avariados num Ponto Eletrão ou numa loja de eletrodomésticos.")
    ]

    print("Populating 366 dataset generator...")
    return m1_topics

print("Base Python setup ready.")
