const fs = require('fs');
const path = require('path');

// 366 Unique Topics Data Definition
const MONTH_NAMES = [
  { pt: "Janeiro", en: "January", days: 31, themeId: "hardware-software", themeNum: 1, themeTitlePt: "Hardware e Software", themeTitleEn: "Hardware and Software", badgeColor: "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300", catPt: "Fundamentos de TIC", catEn: "ICT Fundamentals", icon: "Monitor" },
  { pt: "Fevereiro", en: "February", days: 29, themeId: "ergonomia", themeNum: 2, themeTitlePt: "Ergonomia e Saúde Digital", themeTitleEn: "Ergonomics & Digital Health", badgeColor: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300", catPt: "Ergonomia e Postura", catEn: "Ergonomics & Posture", icon: "Heart" },
  { pt: "Março", en: "March", days: 31, themeId: "palavras-passe", themeNum: 3, themeTitlePt: "Palavras-passe e Autenticação", themeTitleEn: "Passwords & Authentication", badgeColor: "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300", catPt: "Segurança de Acessos", catEn: "Access Security", icon: "KeyRound" },
  { pt: "Abril", en: "April", days: 30, themeId: "seguranca", themeNum: 4, themeTitlePt: "Segurança e Privacidade Online", themeTitleEn: "Online Safety & Privacy", badgeColor: "bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300", catPt: "Proteção Digital", catEn: "Digital Protection", icon: "ShieldCheck" },
  { pt: "Maio", en: "May", days: 31, themeId: "correio-eletronico", themeNum: 5, themeTitlePt: "Correio Eletrónico e Comunicação", themeTitleEn: "Email & Communication", badgeColor: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/40 dark:text-indigo-300", catPt: "Comunicação Digital", catEn: "Digital Communication", icon: "Mail" },
  { pt: "Junho", en: "June", days: 30, themeId: "navegar-internet", themeNum: 6, themeTitlePt: "Navegar na Internet e Pesquisa", themeTitleEn: "Web Browsing & Research", badgeColor: "bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300", catPt: "Pesquisa na Web", catEn: "Web Search", icon: "Globe" },
  { pt: "Julho", en: "July", days: 31, themeId: "direitos-autor", themeNum: 7, themeTitlePt: "Direitos de Autor e Licenciamento", themeTitleEn: "Copyright & Licensing", badgeColor: "bg-rose-100 text-rose-800 dark:bg-rose-900/40 dark:text-rose-300", catPt: "Ética e Licenciamento", catEn: "Ethics & Licensing", icon: "Copyright" },
  { pt: "Agosto", en: "August", days: 31, themeId: "ficheiros-nuvem", themeNum: 8, themeTitlePt: "Ficheiros, Organização e Nuvem", themeTitleEn: "Files, Organization & Cloud", badgeColor: "bg-cyan-100 text-cyan-800 dark:bg-cyan-900/40 dark:text-cyan-300", catPt: "Gestão de Ficheiros", catEn: "File Management", icon: "Folder" },
  { pt: "Setembro", en: "September", days: 30, themeId: "cidadania-digital", themeNum: 9, themeTitlePt: "Cidadania Digital e Netiqueta", themeTitleEn: "Digital Citizenship & Netiquette", badgeColor: "bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-300", catPt: "Cidadania Digital", catEn: "Digital Citizenship", icon: "Users" },
  { pt: "Outubro", en: "October", days: 31, themeId: "redes-internet", themeNum: 10, themeTitlePt: "Redes e Funcionamento da Internet", themeTitleEn: "Networks & Internet Mechanics", badgeColor: "bg-violet-100 text-violet-800 dark:bg-violet-900/40 dark:text-violet-300", catPt: "Redes e Ligação", catEn: "Networks & Connectivity", icon: "Wifi" },
  { pt: "Novembro", en: "November", days: 30, themeId: "programacao-logica", themeNum: 11, themeTitlePt: "Algoritmos e Pensamento Computacional", themeTitleEn: "Algorithms & Computational Thinking", badgeColor: "bg-orange-100 text-orange-800 dark:bg-orange-900/40 dark:text-orange-300", catPt: "Lógica e Algoritmos", catEn: "Logic & Algorithms", icon: "Cpu" },
  { pt: "Dezembro", en: "December", days: 31, themeId: "ia-futuro", themeNum: 12, themeTitlePt: "Inteligência Artificial e Tecnologias", themeTitleEn: "Artificial Intelligence & Tech", badgeColor: "bg-fuchsia-100 text-fuchsia-800 dark:bg-fuchsia-900/40 dark:text-fuchsia-300", catPt: "Tecnologia e Futuro", catEn: "Technology & Future", icon: "Sparkles" }
];

console.log("Monthly specs ready.");
